test: rust python js kotlin flutter swift csharp

rust:
	cd rust && cargo build

python:
	bash python/check.sh

js:
	bash js/check.sh

kotlin:
	cd kotlin && ./gradlew build

csharp:
    cd csharp && dotnet build

flutter:
	bash flutter/check.sh

[macos]
swift:
	cd swift && swift build

[linux]
swift:
    @echo "This command is not supported on Linux platforms (require macOS)."

[windows]
swift:
    @echo "This command is not supported on Windows platforms (require macOS)."
