[package]
name = "snippets-rust"
version = "0.1.0"
edition = "2021"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[dependencies]
nostr-sdk = { version = "0.40", features = ["all-nips"] }
nostr-relay-builder = "0.40"
nwc = "0.40"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
