[package]
name = "nostr-book-snippets"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nostr = { version = "0.45", features = ["os-rng"] }
# ANCHOR: gossip-memory-dependency
nostr-gossip-memory = "0.45"
# ANCHOR_END: gossip-memory-dependency
# ANCHOR: gossip-sqlite-dependency
nostr-gossip-sqlite = "0.45"
# ANCHOR_END: gossip-sqlite-dependency
# ANCHOR: database-dependency
nostr-lmdb = "0.45"
# ANCHOR_END: database-dependency
# ANCHOR: relay-dependency
nostr-sdk = { version = "0.45", features = ["local-relay"] }
# ANCHOR_END: relay-dependency
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
