name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install just
        run: cargo install just

      - name: Check
        run: just build

      - name: Upload built book
        uses: actions/upload-artifact@v4
        with:
          name: built-book
          path: ./output/html

  check-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        working-directory: snippets/rust
        run: cargo build

  check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check
        working-directory: snippets/python
        run: bash check.sh

  check-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        working-directory: snippets/js
        run: bash check.sh

  check-kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Required for kotlin snippets
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Check
        working-directory: snippets/kotlin
        run: ./gradlew build

  check-swift:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        working-directory: snippets/swift
        run: swift build

  check-csharp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Check
        working-directory: snippets/csharp
        run: dotnet build

  check-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Check
        working-directory: snippets/flutter
        run: bash check.sh

  deploy:
    name: Deploy book
    needs: [check-book, check-rust, check-python, check-js, check-kotlin, check-swift, check-csharp, check-flutter]
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built book
        uses: actions/download-artifact@v4
        with:
          name: built-book
          path: ./output/html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
